
data_ingestion:
    test_size: 0.21
    data_url: 'https://raw.githubusercontent.com/aakashaldankar/Albany-Airbnb-Listings-Data/refs/heads/main/listings.csv'

feature_engineering:
    max_features: 20

model_training:                                                                                                                                                                 
      hyper_parameters:
        n_estimators: 200
        max_depth: 6
        learning_rate: 0.1
        subsample: 0.8 
       
tracking_uri:
    "http://127.0.0.1:5000"
