name: CI Pipeline

on: 
  push:
    branches:
      - main

  pull_request: 
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run Ruff Lint
        run: ruff check app src

      - name: Check DVC
        run: | 
          which dvc || echo 'dvc not found'
          dvc --version || true

      - name: Run Unit Tests with Coverage
        run: pytest tests/unit --cov=app --cov=src --cov-report=term-missing --cov-fail-under=65

      - name: Run Integration Tests with Coverage
        run: pytest tests/integration -m 'not slow' --cov=app --cov=src --cov-append --cov-report=term-missing --cov-fail-under=65