name: CI Pipeline

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Check DVC
        run: | 
          which dvc || echo 'dvc not found'
          dvc --version || true

      - name: Run Unit Tests
        run: pytest tests/unit

      - name: Run Integration Tests
        run: pytest tests/integration -m 'not slow'